export const assets = [
  { name: "offscreen_arrow", url: "./offscreen_arrow.png" },
  { name: "ship", url: "./ship.png" },
  { name: "ship_moving", url: "./ship_moving.png" },
  { name: "empty", url: "./empty.png" },
  { name: "shield", url: "./shield.png" },
  { name: "space", url: "./space.png" },
  { name: "planet1", url: "./Baren.png" },
  { name: "planet2", url: "./Ice.png" },
  { name: "planet3", url: "./Lava.png" },
  { name: "planet4", url: "./Terran.png" },
  { name: "explosion1", url: "./explosion/tile000.png" },
  { name: "explosion2", url: "./explosion/tile001.png" },
  { name: "explosion3", url: "./explosion/tile002.png" },
  { name: "explosion4", url: "./explosion/tile003.png" },
  { name: "explosion5", url: "./explosion/tile004.png" },
  { name: "explosion6", url: "./explosion/tile005.png" },
  { name: "explosion7", url: "./explosion/tile006.png" },
  { name: "explosion8", url: "./explosion/tile007.png" },
];
